### ISSUE TITLE
Make App Notification look more mobile friendly

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/team-radio#65]
Make App Notification look more mobile friendly.

## TODO:
- [x] The current app notification is overlapping on the mobile screen. 
- [x] Change the min-height of notification popup.
- [x] Notification background color does not have the core color of application.
