### ISSUE TITLE
Display a notification message when station has a new user joined

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/team-radio#66]
## TODO
- [x] Show notification message when a user joins.
- [x] Fix an issue where the messages always popup every 2 seconds per user.
- [x] Dispatch `Leave Station` action when the station is closed to prevent requesting join station.

Refer to 70d5d55b778317ad0560704862032b6241d8061b  7f1e03faa28065beb84f33b608a0ecc643406381 3b45dd01bde6039445bd2ab09233557d8aa82660
