### ISSUE TITLE
Make station switcher more interactive

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/team-radio#68]
## TODO:
- [x] API `SERVER_UPDATE_STATIONS` return thumbnail of the station which includes the thumbnail of the current playing song.
- [x] Show a sleep icon if any station is NOT playing.
- [x] Show number of users in each station.

**Comment by chienthangplus** [comment]
#78 
 API SERVER_UPDATE_STATIONS return thumbnail of the station which includes the thumbnail of the current playing song.

**Comment by pvtri96** [comment]
Tested & reviewed by @pvtri96 @NguyenTatNhac & @chienthangplus 
Close #68

**Comment by pvtri96** [comment]
Reopen #68
@binhpv want a moving, animating or playing icon that displays on each station to know exactly which station is playing & which is NOT.

**Comment by pvtri96** [comment]
I will move `playing icon on switcher` to another issue. Close #68
